server:
  port: 8082
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///yun6
    username: root
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: com.leyou.item.pojo
